# Generated by Django 6.0.3 on 2026-03-19 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LivreStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Statut de livre",
                "verbose_name_plural": "Statuts de livres",
            },
        ),
        migrations.CreateModel(
            name="LivreType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Type de livre",
                "verbose_name_plural": "Types de livres",
            },
        ),
        migrations.CreateModel(
            name="Livre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "livre_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="livres",
                        to="backoffice.livrestatus",
                    ),
                ),
                (
                    "livre_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="livres",
                        to="backoffice.livretype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livre",
                "verbose_name_plural": "Livres",
                "ordering": ["nom"],
            },
        ),
    ]
